### ISSUE TITLE
Difference between CE and MG Monte-Carlo

### ISSUE THREAD

**Issue by KseniaBastrakova** [openmc-dev/openmc#1837] opened 2021-05-12 11:57 UTC
Hello,

I'm comparing two algorithms: Continuous energy Monte-Carlo and Multi-Group Monte-Carlo in openMC with different number of groups. A pin-cell model with two materials and reflective boundary conditions is used.
And I see a significant difference in the results as the number of groups increases. 

i tried measurings with CASMO structures, but change first group from **1.0000000000E+01** to **20000000000E+01**
and with
```
batches = 1000
inactive = 100
particles = 40000
```

and i got next results, that show significant increasing of bias.
Do you have any idea why this is happening? Or maybe publications comparing the two methods?
Thanks in advance for your reply.

group structure |  bias [pcm]
------------- | -------------
2 groups CASMO | 32.2
4 groups CASMO  |  82.7
8 groups CASMO | 158.2
70 groups CASMO | 198

standart deviation for **CE** = 13 [pcm]
standart deviation for **MG** form 9.4 to 12 [pcm]

Here are python code, that i used to make this calculations:
also, i attached me python file to issue:
[mg_measurings.zip](https://github.com/openmc-dev/openmc/files/6466021/mg_measurings.zip)

I initialize pinCell model with two materials:

```

python
fuel = openmc.Material(name='1.6% Fuel')
fuel.set_density('g/cm3', 10.31341)
fuel.add_nuclide('U235', 3.7503e-4)
fuel.add_nuclide('U238', 2.2625e-2)
fuel.add_nuclide('O16', 4.6007e-2)

water = openmc.Material(name='Borated Water')
water.set_density('g/cm3', 0.740582)
water.add_nuclide('H1', 4.9457e-2)
water.add_nuclide('O16', 2.4732e-2)
materials_file = openmc.Materials([fuel, water])
fuel_radius = openmc.ZCylinder(x0=0.0, y0=0.0, r=0.39218)
box = openmc.model.rectangular_prism(1.26, 1.26, boundary_type='reflective')
pin_cell_universe = openmc.Universe(name='1.6% Fuel Pin')
fuel_cell = openmc.Cell(name='1.6% Fuel')
fuel_cell.fill = fuel
fuel_cell.region = -fuel_radius
pin_cell_universe.add_cell(fuel_cell)
moderator_cell = openmc.Cell(name='1.6% Moderator')
moderator_cell.fill = water
moderator_cell.region = +fuel_radius & box
pin_cell_universe.add_cell(moderator_cell)
openmc_geometry = openmc.Geometry(pin_cell_universe)
```

Next, i make mgxs structure:

```python
groups = openmc.mgxs.EnergyGroups([0.0, 0.058, 0.14, 0.28, 0.625, 4.0, 5530.0, 821000.0, 20000000.0])
mgxs_lib = openmc.mgxs.Library(openmc_geometry)
mgxs_lib.energy_groups = groups
mgxs_lib.mgxs_types = ['total', 'absorption', 'nu-fission', 'fission',
                       'nu-scatter matrix', 'multiplicity matrix', 'chi']

mgxs_lib.domain_type = "cell"
mgxs_lib.domains = openmc_geometry.get_all_cells().values()
mgxs_lib.by_nuclide = False
mgxs_lib.legendre_order = 3
mgxs_lib.check_library_for_openmc_mgxs()
mgxs_lib.build_library()
```

Run simulation:

```python
from random import randint
batches = 1000
inactive = 100
particles = 40000

settings_file = openmc.Settings()
settings_file.batches = batches
settings_file.inactive = inactive
settings_file.particles = particles
settings_file.output = {'tallies': False}
settings_file.seed = randint(0, 100)


bounds = [-0.63, -0.63, -0.63, 0.63, 0.63, 0.63]
uniform_dist = openmc.stats.Box(bounds[:3], bounds[3:], only_fissionable=True)
settings_file.source = openmc.Source(space=uniform_dist)
openmc.run()

```

And run in Multi-group mode:

```python
          

sp = openmc.StatePoint(ce_spfile, autolink=False)
su = openmc.Summary(ce_sumfile)
sp.link_with_summary(su)
mgxs_lib.load_from_statepoint(sp)
mgxs_file = mgxs_lib.create_mg_library(xs_type='macro', xsdata_names=['fuel', 'water'])
mgxs_file.export_to_hdf5()

fuel_mg = openmc.Material(name='UO2', material_id=1)
fuel_mg.add_macroscopic('fuel')
water_mg = openmc.Material(name='Water', material_id=2)
water_mg.add_macroscopic('water')
materials_file = openmc.Materials([fuel_mg, water_mg])
materials_file.cross_sections = 'mgxs.h5'
settings_file.energy_mode = 'multi-group'
settings_file.seed = randint(0, 100)
openmc.run()
```

and compare results:
```python
mgsp = openmc.StatePoint(mg_spfile, autolink=False)

mgsu = openmc.Summary(mg_sumfile)
mgsp.link_with_summary(mgsu)
mg_keff = mgsp.k_combined
ce_keff = sp.k_combined
bias = 1.0E5 * (ce_keff - mg_keff)
print('Continuous-Energy keff = {0:1.6f}'.format(ce_keff))
print('Multi-Group keff = {0:1.6f}'.format(mg_keff))
print('bias [pcm]: {0:1.1f}'.format(bias.nominal_value))
```

**Comment by nelsonag** [comment] 2021-05-12 13:27
Hi @KseniaBastrakova; we keep issues for identification and tracking of software enhancements/bugs. This topic is best placed at the OpenMC discussion group (https://openmc.discourse.group/) where many more folks can help providing feedback than would be the case here. 

I will close this issue but will post the following advice which may be useful:

1. Remove settings_file.seed, or, set it to a constant for the purposes of identifying the source of the bias' behavior. This will have no bearing on the behavior you see, but will make the next steps _not_ attributable to changes in the random number stream, and thus more comparable.
2. The MG keff reported by OpenMC as +/- 9.4 to 12 pcm does not include any information about the stochastic uncertainty present in the MGXS due to their tallying. That stochastic uncertainty will grow with the number of energy groups.  I recommend increasing the number of particles, especially in the higher group cases.
3. As discussed in #1813, using ``openmc_geometry.get_all_cells().values()`` to set the ``mgxs_lib.domains`` attribute may result in the intended ordering of domains not being maintained. In effect this means the MGXS set named 'fuel' could actually be from the water cell, and vice versa. To be sure this isn't the cause, switch the ``mgxs_lib.domains = openmc_geometry.get_all_cells().values()`` line to be ``mgxs_lib.domains = [fuel_cell, moderator_cell]``. I don't expect this to be the cause of what you are seeing, but we should be sure.
4. A P3 Legendre expansion is applied in the MGXS and the OpenMC MG mode. As the number of groups increases, this Legendre expansion is more likely to have negative valued regions of the expanded scattering distribution. The MG transport will not sample a negative probability distribution in a way that preserves the probabilities which will manifest in a bias. To get around this, you can replace ``mgxs_lib.legendre_order = 3`` with:

```python
mgxs_lib.scatter_format = 'histogram'
mgxs_lib.histogram_bins = 11
```
11 bins will generally suffice, but this can be tweaked as needed. Using histogram bins avoids the possibility of negative scattering angle probability distribution functions altogether for a more direct comparison of groups.

If those don't provide any use, then it is likely just a cancellation of error you are observing. Something similar was found here (though not for a pin cell): https://www.mdpi.com/2673-4362/2/1/9  .

**Closed by nelsonag** 2021-05-12 13:27 UTC

**Comment by KseniaBastrakova** [comment] 2021-05-12 14:07
At first thanks for the detailed answer! It's really helpful, i'm going to check everything. Sorry, i did't know about this possibility, next time i will ask here.
