### ISSUE TITLE
Fixed source sampling doesnt fit within current bank model

### ISSUE THREAD

**Issue by makeclean** [openmc-dev/openmc#1364] opened 2019-09-24 21:08 UTC
The current mechanism by which particles are sampled within a fixed source problem is not ideal. There is an effective limit on the number of primary histories that can be simulated, this is somewhere in the region of 1e9-5e9 primaries depending upon your system memory. Modications should address this situation, such that the transport loop looks to take particles from the seconday bank, and if none are available generate a new primary.

**Comment by simondrichards** [comment] 2020-01-28 16:00
@paulromano , 
My colleague @davidjohnlong is going to have a look at this Issue. I guess I don't have write permission to assign him to the issue. Could you, or anyone else with the necessary permission, please assign him? Thanks.

**Comment by paulromano** [comment] 2020-01-28 16:24
In order to assign him, he needs to be a member on the github openmc organization first -- I've just sent him an invite so once he accepts, I should be able to assign him.

**Comment by davidjohnlong** [comment] 2020-02-03 14:20
@paulromano 
Hi Paul. 

I have accepted your invite to the GitHub openmc organization and am going to make a start on this issue over the next few days if you would like to assign it to me please. 

Regards,
David

**Comment by davidjohnlong** [comment] 2020-02-26 12:49
@paulromano @simondrichards @makeclean 

Apologies for the slow progress on this. I have been on paternity leave for the last few weeks but yesterday I was able to have a more detailed look at this issue. 

While the requested improvements to the fixed source sampling is relatively straight forward when sampling source particles from external distributions, I believe that the situation is a little more complex when read/writing source particles from a statepoint/source file. 

For the case of external distributions I think that the memory constraint of defining/populating the primary bank for each particle before the particle loop could be eliminated though sampling "as needed" for each particle at the start of initialize_history(). This would replace the indexing of the primary source bank which currently occurs. This should be a relatively unintrusive change and would fit within the existing OpenMP implementation.  

For the case when source particles are read/written from a file. If we are requiring that the primary bank is not defined/populated before the particle loop then the sampling of particles "as needed" will require incremental I/O to appropriate files within an active OpenMP region and therefore will need to be synchronised between threads using a critical construct, which could occur a performance penalty. What are your thoughts on this? Is this something that you think that we should be concern about and/or should be considered when approaching the modifications for this issue.    

Before I start to make significant changes to the code I think it is best that we agree on the approach. 

Kind regards,
David

**Comment by simondrichards** [comment] 2020-02-26 20:42
In a fixed source calculation you don't really need batches in the same way that you do in an eigenvalue calculation, because you don't need source iteration. But there may be other arguments for retaining batches (e.g. it might help to avoid loss of floating point precision if you tally in batches then add batches to cumulative tallies. You might also want the capability for restarting a calculation from a statepoint file rather than rerunning the whole thing). And, as Dave says, you don't really need source banks because you can sample source particles when they are needed at the start of each history.

So in many ways getting rid of the source banks in favour of sampling source particles at the start of each history makes a lot of sense for fixed source calculations. But what about writing the source to statepoint/source files and reading the source from statepoint/source files? Dave has pointed out some issues here. But could we consider an alternative to storing individual source particles in files? Instead we could consider storing the source description (distributions in space, angle, and energy, etc.) in the statepoint file. If we now have a separate random number stream specifically for source particle sampling, and we store the state of this random number generator in the statepoint file, then we can always regenerate the same sequence of source particles on demand without having to store all of the source particles individually.

Just putting these ideas out there for discussion.

**Comment by Shimwell** [comment] 2020-03-03 10:07
Perhaps this issue is one for slack or even a quick conference call

**Comment by davidjohnlong** [comment] 2020-03-03 10:35
@Shimwell  
Hi Jonathan. I will set up a slack channel, see what people's general thoughts are and then we can have a conference call if needed.

David

**Comment by paulromano** [comment] 2020-03-03 12:26
I agree with @simondrichards that in the case of a fixed source calculation, there isn't really a need for storing source sites in the statepoint file. The primary purpose of storing the source is so that you can restart a simulation at a given point and still retain reproducibility. In the case of a fixed source calculation, all that's really needed is (as @simondrichards points out) the RNG state, which can be determined just by the number of batches.

We could (and may want to) store the external source parameters, perhaps in the summary.h5 file, but strictly speaking, I don't think we'll need to for the sake of restart runs. Right now, `settings.xml` will still be read during a restart run and so as long as the user doesn't change the external source in their settings, the restart run will pick up the same source.

Regarding batching in general, there are some benefits to it even for fixed source calculations. For one, if you run a problem with many tallies and you don't use batching, you will have to accumulate each and every tally bin after each history (you could hypothetically get around this by keeping a dynamic list of the bins that were scored to, but that gets a little complicated). Batching significantly reduces the frequency at which you have to do tally accumulation. The other benefit is that by grouping histories together in a batch, you are more or less guaranteed to get a normal distribution for all your tally scores, which helps ensure that you can put together confidence intervals that are meaningful. Without batching, you could in theory end up with a distribution of scores that is decidedly non-normal.

**Comment by davidjohnlong** [comment] 2020-03-03 14:50
@paulromano 
Thanks for the clarification. If you are happy that the settings.xml file is required to be present and read for a restart run then as stated it is only the case of ensuring the RNG state is correct and sampling performed at the start of each history. As you say we can always add the saving of source parameters at a later date. 

I still have a question about how this should be implemented from an application point of view, i.e. are we requiring that the modified code still be back compatible with the existing bank model and give the user the option to select the new "memory-efficient" sampling? Or is this going to be hard-coded and out of scope of the user control? 

I think that probably the cleanest approach is to have an additional flag in the settings.xml file which selects the new sampling model, and which correctly sets additional flags to ensure that source particles can not be read/written to files. However, this choice is ultimately yours.

David

**Comment by paulromano** [comment] 2020-03-03 16:24
Personally, I wouldn't worry about backwards compatibility in this case. Unless there's a good reason, better to leave this kind of baggage behind. To my knowledge, we don't have as many users of the code hammering on fixed source problems, so my guess is that no one will even notice (other than the folks in the fusion community who will appreciate the change!).

**Comment by davidjohnlong** [comment] 2020-03-03 16:30
Ok. Not having details of the user community I thought it was better to ask. I will get on with the changes now.

**Comment by paulromano** [comment] 2020-04-21 18:56
Closed with the merging of #1518

**Closed by paulromano** 2020-04-21 18:56 UTC
Labels: Other Enhancement
