### ISSUE TITLE
Long material names in DAGMC OpenMC bug

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1372] opened 2019-10-07 14:32 UTC
I think I have stumbled across a tiny bug in the DAGMC implementation within OpenMC

DAGMC has limits to the length of a material name (32 characters but really 28 once the mat: is included)

It looks like it is possible to assign a long material name to a h5m file using trelis/cubit and then assign a long material name in openmc materials.xml and run the simulation. This uses the "legacy" mode DAGMC workflow not the UW2 which would probably pick up this error.

OpenMC doesn't appear to notice that the material is not found in the geometry. The volume with the long material name don't get any particle interactions.

Perhaps one solution would be to prevent OpenMC using long material names when being used in DAGMC mode but @pshriwise and @makeclean are the experts here

I think this is the PR that allowed the material names to be used [PR](https://github.com/openmc-dev/openmc/pull/1199) perhaps adding a material name length check to src/dagmc.cpp could be sufficient

**Comment by Shimwell** [comment] 2019-10-07 14:36
Here are a couple of examples when the heating tally gets no results when long material name is used and results when a short material name is used

Example geometry with short material names
https://drive.google.com/open?id=1XPCYG5p2DhjveaKsP4pdbV64feqGy9DD


Example geometry with long material names
https://drive.google.com/open?id=1MgmM_UDW3uMPwUL-JFyzYuvfJvk1Maci

**Comment by pshriwise** [comment] 2019-10-07 20:14
Thanks for reporting and providing examples @Shimwell! I'm looking into it now and will get back to you shortly

**Comment by pshriwise** [comment] 2019-10-07 21:11
So I think the problem is that the word "vacuum" is in one of the material names. Currently, any names that *contain* "vacuum", "graveyard", or "void" will be assigned to a void material. I updated the material name in the long name to something of an equivalent length that did not contain "vacuum" and got the same result as the short name problem.

I think the answer here is to check for those exact strings rather than a substring in the material name. I'll submit a PR to that effect soon.

**Comment by Shimwell** [comment] 2019-10-07 21:22
Ah these keyword in the substring tricks are sneaky traps. Thanks for identifying the problem correctly, @makeclean will be delighted.

I would have thought that the material can contain these keywords within part of the string but not exactly match them.

**Comment by pshriwise** [comment] 2019-10-07 21:42
Agreed, for sure. I'll correct that asap.

**Comment by makeclean** [comment] 2019-10-15 12:52
This was fixed with #1375

**Closed by makeclean** 2019-10-15 12:52 UTC
