### ISSUE TITLE
Incorrect  tally results when separating model into many cells?

### ISSUE THREAD

**Issue by D-Benjamin** [openmc-dev/openmc#1204] opened 2019-03-26 09:03 UTC
Hi All,
    I wanna get the power density in a reactor core by using OpenMC tally, so I separated my model into many cells. By using "kappa-fission" tally to get the energy located in different cells. The energy I get by "kappa-fission" tally has the units [eV/source]. And then, I multiply it by (P * nu/(Q * k)), which has the units [source/s]. Finally, I get the power which has the units [eV/s], that is can be converted to [W]. By divided it by volume of each cell, the power density[W/m3] finally can be converted by "kappa-fission" tally. However, I found it may be a bug when tally in a separated cells. 
    I did a test by a simple cylinder model, by separated it into nine cells(There are three cells in the axial and radial directions, respectively). However, I found the maximum tally is not located in the center of cylinder, so as the power density. I reckon it's a tally bug.
    Here is my script:
```
import openmc

# define materials
materials_file = openmc.Materials()

fuelSalt = []
i = 0
while i < 9:
    x = openmc.Material(i+1, "fuel salt{0}".format(i))
    fuelSalt.append(x)
    fuelSalt[i].add_nuclide('Li6', 1.4485e-5)
    fuelSalt[i].add_nuclide('Li7', 28.9685515e-2)
    fuelSalt[i].add_nuclide('F19', 0.6262)
    fuelSalt[i].add_nuclide('Th232', 7.47e-2)
    fuelSalt[i].add_nuclide('U233', 9.4e-3)
    # fuelSalt[i].add_s_alpha_beta('c_Li_in_LiF')
    # fuelSalt[i].add_s_alpha_beta('c_F_in_LiF')
    fuelSalt[i].set_density('g/cm3', 4.125)
    fuelSalt[i].temperature = 973
    materials_file.append(fuelSalt[i])
    i = i + 1

materials_file.cross_sections = "/home/benjamin/MSR_lib/cross_sections.xml"
materials_file.export_to_xml()

# define geometry
r1 = openmc.ZCylinder(x0=0.0, y0=0.0, R=37.58)
r2 = openmc.ZCylinder(x0=0.0, y0=0.0, R=75.16)
# r3 = openmc.ZCylinder(x0=0.0, y0=0.0, R=112.75, boundary_type='reflective')
r3 = openmc.ZCylinder(x0=0.0, y0=0.0, R=112.75, boundary_type='vacuum')

z6 = openmc.ZPlane(z0=225.5, boundary_type='reflective')
zx2 = openmc.ZPlane(z0= 150.333)
zx1 = openmc.ZPlane(z0= 75.167)
z0 = openmc.ZPlane(z0=0, boundary_type='reflective')

core_region = []
core_region.append(+z0 & -zx1 & -r1)
core_region.append(+z0 & -zx1 & +r1 & -r2)
core_region.append(+z0 & -zx1 & +r2 & -r3)
core_region.append(+zx1 & -zx2 & -r1)
core_region.append(+zx1 & -zx2 & +r1 & -r2)
core_region.append(+zx1 & -zx2 & +r2 & -r3)
core_region.append(+zx2 & -z6 & -r1)
core_region.append(+zx2 & -z6 & +r1 & -r2)
core_region.append(+zx2 & -z6 & +r2 & -r3)

univ = openmc.Universe(universe_id=0)

core_cell = []
i = 0
while i < 9:
    x = openmc.Cell(i, name='core{0}'.format(i), fill=fuelSalt[i])
    core_cell.append(x)
    core_cell[i].region = core_region[i]
    univ.add_cell(core_cell[i])
    i =i + 1

geom = openmc.Geometry(univ)
geom.export_to_xml()

# define settings
settings = openmc.Settings()
point = openmc.stats.Point((0, 0, 112.75))
src = openmc.Source(space=point)
settings.source = src
settings.particles = 100000
settings.batches = 1500
settings.inactive = 300
settings.output = {'tallies':True}
settings.resonance_scattering = {"enable":True, "method":"dbrc"}
settings.temperature = {"multipole":False, "method":"interpolation"}
settings.export_to_xml()

# define tallies
tallies = openmc.Tallies()
core_filter = []
core_kappa = []
core_nuFiss = []
core_fiss = []
i = 0
while i < 9:
    x1 = openmc.CellFilter([core_cell[i]])
    # x1 = openmc.MaterialFilter([fuelSalt[i]])
    x2 = openmc.Tally(name='core kappa{0}'.format(i))
    x3 = openmc.Tally(name='core nu-fission{0}'.format(i))
    x4 = openmc.Tally(name='core fiss rate{0}'.format(i))
    core_filter.append(x1)
    core_kappa.append(x2)
    core_kappa[i].filters = [core_filter[i]]
    core_kappa[i].scores = ['kappa-fission']
    core_nuFiss.append(x3)
    core_nuFiss[i].filters = [core_filter[i]]
    core_nuFiss[i].scores = ['nu-fission']
    core_fiss.append(x4)
    core_fiss[i].filters = [core_filter[i]]
    core_fiss[i].scores = ['fission']
    tallies += (core_kappa[i], core_nuFiss[i], core_fiss[i])
    i = i + 1

tallies.export_to_xml()

# p1 = openmc.Plot()
# p1.filename = 'cylinder-xz'
# p1.origin = [0, 0, 225.5/2]
# p1.width = [112.75*2, 225.5]
# p1.basis = 'xz'
# p1.color_by = 'material'
# plot_file = openmc.Plots([p1])
# plot_file.export_to_xml()
# openmc.plot_geometry()
# openmc.plot_inline(p1)

openmc.run()
```

The power density[W/m3] as below:
```
67414    47999    17263
68193    48357    17354
68514    48640    17463
```
68193 is the power density of the center of cylinder, which is lower than the same radial but different height cells' value.
 Any reply will be great appreciated!

Best Regards
Benjamin

**Comment by D-Benjamin** [comment] 2019-03-26 11:12
By the way, the OpenMC version I'm using is [v.0.10.0(develop branch)](https://github.com/openmc-dev/openmc)

**Comment by paulromano** [comment] 2019-03-26 12:13
Hi @D-Benjamin. Using the latest developmental branch of OpenMC, I was not able to reproduce the result you are seeing. I see the highest power density in the center cell. When you were looking at results, did you use the settings from this script or did you run fewer particles?

**Comment by D-Benjamin** [comment] 2019-03-26 12:26
Hi @paulromano , I tested differents cases, the particles were 50 thousand, 5 billion and 5 million, respectively. So I think the particles are enough(5 million). I uninstalled the develop branch, and reinstalled openmc by "conda install openmc" one hour ago. Now my version is v.0.10.0, but I still cannot get highest power density in the center model. Do you means that you can get the highest power density in the center model?  What is your version?
Thank you!

**Comment by paulromano** [comment] 2019-03-26 12:34
@D-Benjamin I am using the `develop` branch, and yes, I get the highest power density in the center. Can you attach your tallies.out file from when you run?

**Comment by D-Benjamin** [comment] 2019-03-26 12:52
Hi @paulromano, Some tallies.out had been clean, I only have two "tallies.out" results.
Following is the result with 50 thousand particles and 500 batches(inactive 50), the openmc version is the v.0.10.0, which I reinstalled by  "conda install openmc" one hour ago:

```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.74648E+06    +/- 8723.92

 ===================>     TALLY 2: CORE NU-FISSION0     <===================

 Cell 0
   Total Material
     Nu-Fission Rate                      7.52065E-02    +/- 1.14061E-04

 ===================>     TALLY 3: CORE FISS RATE0     <====================

 Cell 0
   Total Material
     Fission Rate                         3.00561E-02    +/- 4.56273E-05

 =====================>     TALLY 4: CORE KAPPA1     <======================

 Cell 1
   Total Material
     Kappa-Fission Rate                   1.22351E+07    +/- 15592.4

 ===================>     TALLY 5: CORE NU-FISSION1     <===================

 Cell 1
   Total Material
     Nu-Fission Rate                      0.160124       +/- 2.03870E-04

 ===================>     TALLY 6: CORE FISS RATE1     <====================

 Cell 1
   Total Material
     Fission Rate                         6.39938E-02    +/- 8.15511E-05

 =====================>     TALLY 7: CORE KAPPA2     <======================

 Cell 2
   Total Material
     Kappa-Fission Rate                   7.31426E+06    +/- 10620.5

 ===================>     TALLY 8: CORE NU-FISSION2     <===================

 Cell 2
   Total Material
     Nu-Fission Rate                      9.57287E-02    +/- 1.38800E-04

 ===================>     TALLY 9: CORE FISS RATE2     <====================

 Cell 2
   Total Material
     Fission Rate                         3.82563E-02    +/- 5.55461E-05

 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.82307E+06    +/- 6874.80

 ==================>     TALLY 11: CORE NU-FISSION3     <===================

 Cell 3
   Total Material
     Nu-Fission Rate                      7.62087E-02    +/- 8.97839E-05

 ===================>     TALLY 12: CORE FISS RATE3     <===================

 Cell 3
   Total Material
     Fission Rate                         3.04567E-02    +/- 3.59550E-05

 =====================>     TALLY 13: CORE KAPPA4     <=====================

 Cell 4
   Total Material
     Kappa-Fission Rate                   1.23881E+07    +/- 9481.41

 ==================>     TALLY 14: CORE NU-FISSION4     <===================

 Cell 4
   Total Material
     Nu-Fission Rate                      0.162127       +/- 1.23839E-04

 ===================>     TALLY 15: CORE FISS RATE4     <===================

 Cell 4
   Total Material
     Fission Rate                         6.47942E-02    +/- 4.95870E-05

 =====================>     TALLY 16: CORE KAPPA5     <=====================

 Cell 5
   Total Material
     Kappa-Fission Rate                   7.42755E+06    +/- 7058.09

 ==================>     TALLY 17: CORE NU-FISSION5     <===================

 Cell 5
   Total Material
     Nu-Fission Rate                      9.72108E-02    +/- 9.22126E-05

 ===================>     TALLY 18: CORE FISS RATE5     <===================

 Cell 5
   Total Material
     Fission Rate                         3.88488E-02    +/- 3.69143E-05

 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.87579E+06    +/- 8801.67

 ==================>     TALLY 20: CORE NU-FISSION6     <===================

 Cell 6
   Total Material
     Nu-Fission Rate                      7.68977E-02    +/- 1.15025E-04

 ===================>     TALLY 21: CORE FISS RATE6     <===================

 Cell 6
   Total Material
     Fission Rate                         3.07324E-02    +/- 4.60333E-05

 =====================>     TALLY 22: CORE KAPPA7     <=====================

 Cell 7
   Total Material
     Kappa-Fission Rate                   1.24773E+07    +/- 14614.9

 ==================>     TALLY 23: CORE NU-FISSION7     <===================

 Cell 7
   Total Material
     Nu-Fission Rate                      0.163295       +/- 1.91081E-04

 ===================>     TALLY 24: CORE FISS RATE7     <===================

 Cell 7
   Total Material
     Fission Rate                         6.52607E-02    +/- 7.64376E-05

 =====================>     TALLY 25: CORE KAPPA8     <=====================

 Cell 8
   Total Material
     Kappa-Fission Rate                   7.49181E+06    +/- 9090.28

 ==================>     TALLY 26: CORE NU-FISSION8     <===================

 Cell 8
   Total Material
     Nu-Fission Rate                      9.80527E-02    +/- 1.18819E-04

 ===================>     TALLY 27: CORE FISS RATE8     <===================

 Cell 8
   Total Material
     Fission Rate                         3.91849E-02    +/- 4.75430E-05
```

This one is the result with 100 thousand particles and 1500 batches(Namely, the script above), the openmc version is the v.0.10.0(develop branch):

```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.74648E+06    +/- 8723.92

 ===================>     TALLY 2: CORE NU-FISSION0     <===================

 Cell 0
   Total Material
     Nu-Fission Rate                      7.52065E-02    +/- 1.14061E-04

 ===================>     TALLY 3: CORE FISS RATE0     <====================

 Cell 0
   Total Material
     Fission Rate                         3.00561E-02    +/- 4.56273E-05

 =====================>     TALLY 4: CORE KAPPA1     <======================

 Cell 1
   Total Material
     Kappa-Fission Rate                   1.22351E+07    +/- 15592.4

 ===================>     TALLY 5: CORE NU-FISSION1     <===================

 Cell 1
   Total Material
     Nu-Fission Rate                      0.160124       +/- 2.03870E-04

 ===================>     TALLY 6: CORE FISS RATE1     <====================

 Cell 1
   Total Material
     Fission Rate                         6.39938E-02    +/- 8.15511E-05

 =====================>     TALLY 7: CORE KAPPA2     <======================

 Cell 2
   Total Material
     Kappa-Fission Rate                   7.31426E+06    +/- 10620.5

 ===================>     TALLY 8: CORE NU-FISSION2     <===================

 Cell 2
   Total Material
     Nu-Fission Rate                      9.57287E-02    +/- 1.38800E-04

 ===================>     TALLY 9: CORE FISS RATE2     <====================

 Cell 2
   Total Material
     Fission Rate                         3.82563E-02    +/- 5.55461E-05

 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.82307E+06    +/- 6874.80

 ==================>     TALLY 11: CORE NU-FISSION3     <===================

 Cell 3
   Total Material
     Nu-Fission Rate                      7.62087E-02    +/- 8.97839E-05

 ===================>     TALLY 12: CORE FISS RATE3     <===================

 Cell 3
   Total Material
     Fission Rate                         3.04567E-02    +/- 3.59550E-05

 =====================>     TALLY 13: CORE KAPPA4     <=====================

 Cell 4
   Total Material
     Kappa-Fission Rate                   1.23881E+07    +/- 9481.41

 ==================>     TALLY 14: CORE NU-FISSION4     <===================

 Cell 4
   Total Material
     Nu-Fission Rate                      0.162127       +/- 1.23839E-04

 ===================>     TALLY 15: CORE FISS RATE4     <===================

 Cell 4
   Total Material
     Fission Rate                         6.47942E-02    +/- 4.95870E-05

 =====================>     TALLY 16: CORE KAPPA5     <=====================

 Cell 5
   Total Material
     Kappa-Fission Rate                   7.42755E+06    +/- 7058.09

 ==================>     TALLY 17: CORE NU-FISSION5     <===================

 Cell 5
   Total Material
     Nu-Fission Rate                      9.72108E-02    +/- 9.22126E-05

 ===================>     TALLY 18: CORE FISS RATE5     <===================

 Cell 5
   Total Material
     Fission Rate                         3.88488E-02    +/- 3.69143E-05

 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.87579E+06    +/- 8801.67

 ==================>     TALLY 20: CORE NU-FISSION6     <===================

 Cell 6
   Total Material
     Nu-Fission Rate                      7.68977E-02    +/- 1.15025E-04

 ===================>     TALLY 21: CORE FISS RATE6     <===================

 Cell 6
   Total Material
     Fission Rate                         3.07324E-02    +/- 4.60333E-05

 =====================>     TALLY 22: CORE KAPPA7     <=====================

 Cell 7
   Total Material
     Kappa-Fission Rate                   1.24773E+07    +/- 14614.9

 ==================>     TALLY 23: CORE NU-FISSION7     <===================

 Cell 7
   Total Material
     Nu-Fission Rate                      0.163295       +/- 1.91081E-04

 ===================>     TALLY 24: CORE FISS RATE7     <===================

 Cell 7
   Total Material
     Fission Rate                         6.52607E-02    +/- 7.64376E-05

 =====================>     TALLY 25: CORE KAPPA8     <=====================

 Cell 8
   Total Material
     Kappa-Fission Rate                   7.49181E+06    +/- 9090.28

 ==================>     TALLY 26: CORE NU-FISSION8     <===================

 Cell 8
   Total Material
     Nu-Fission Rate                      9.80527E-02    +/- 1.18819E-04

 ===================>     TALLY 27: CORE FISS RATE8     <===================

 Cell 8
   Total Material
     Fission Rate                         3.91849E-02    +/- 4.75430E-05
```

**Comment by paulromano** [comment] 2019-03-26 13:00
A snippet of what I get:
```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.35986e+06 +/- 54086
...
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.87607e+06 +/- 45256.9
...
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.58419e+06 +/- 69004.5
```

Is it possible for you to retry the simulation using the develop branch?

**Comment by D-Benjamin** [comment] 2019-03-26 13:06
Ok, I'll reinstall the develop branch, and disscuss with you later, thanks, paulromano!

**Comment by D-Benjamin** [comment] 2019-03-26 15:11
Hi @paulromano , I reinstalled the develop branch and retried the simulation. This time, I get the reasonable than any of the previous ones(At least, the highest power density is located in the center). However, the kappa-fission rate in the cell3 is only a little larger than the cell0 and cell6, I think your result is much better. Because your result shows that kappa-fission rate in the cell3 is larger than the cell0 and cell6 distinctly. I'm afraid that there are still some troubles with it. 
Anyway, I believe that there are some troubles in the develop branch I used before and the v.0.10.0 installed by "conda install openmc".
 ```
=====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.69596e+06 +/- 4063.57
...
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.703e+06 +/- 2993.29
...
=====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.68136e+06 +/- 4231.7
```

The power density[W/m3] as below:
68181 48301 17320
68267 48414 17359
68007 48273 17323

Sincerely
Benjamin

**Comment by D-Benjamin** [comment] 2019-03-27 09:19
Hi, @paulromano , Yesterday, I got just passable result (the kappa-fission rate in the cell3 is only a little larger than the cell0 and cell6). I'm afraid that there are still some troubles with it, so I did three more tests:
Case1: changing another computer, using the script above, the version is 0.10.0(downloaded by "conda install openmc"), here is the result:
 ```
=====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.91352E+06    +/- 22859.0
...
=====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.83969E+06    +/- 21770.0
...
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   6.10741E+06    +/- 24181.9
```

Case2: Increasing the particles to 500 thousand, using the [official nuclear data libraries](https://openmc.mcs.anl.gov), the version is develop branch. Here is the result:
```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.61742e+06 +/- 1996.03
...
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.60789e+06 +/- 1343.79
...
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.60733e+06 +/- 1891.66
```

Case3: Increasing the particles to 500 thousand, using the ENDF-VII.1 data library, which converted by IncidentNeutron.from_njoy . The version is develop branch. Here is the result:
```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.69993e+06 +/- 1754.46
...
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.69262e+06 +/- 1347.76
...
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.68165e+06 +/- 1656.07
```

Unfortunately, three cases' result are all fault. Yesterday's result may be fortuitous. What's your opinion about this? Do you think it's a bug? Or other dependencies, such as python version, uncertainties version? My python version is 3.6.5 and uncertainties version is 3.0.3. Hope to hear from you soon!

Best regards
Benjamin

**Comment by smharper** [comment] 2019-03-27 14:45
Hey @D-Benjamin, when I see a power profile that bounces around like this depending on the input, it's often a sign that the reactor has a sufficiently high dominance ratio that you need _a ton_ of active neutrons per batch.  If there are too few neutrons, the stochastic noise will excite higher order modes and you'll see unconverged power profiles.  For example, on a full-length PWR pin (365cm), I find that something like 1 million particles per batch are necessary to damp those higher order terms below 1% of the fundamental.

One easy way to check for this is to add an entropy mesh and plot the reactor entropy as a function of batches.  If you don't have enough neutrons, you'll find that the entropy never really converges; it'll show sudden drops and jumps no matter how many batches are run.  The entropy check isn't always reliable, but I'd recommend it as a first step.  (Look at the `openmc.Settings` object to see where to add the entropy mesh.)

**Comment by D-Benjamin** [comment] 2019-03-28 15:13
Hi @smharper , Thanks for your suggestion! This time, I set the particles per batch were 1 million, and I added an entropy mesh. Following are the result, can I believe that it have converged? Well, the result is still not correct. The highest power density isn't located in the center. I'll do more test to figure it out. Thank you!
```
Bat./Gen.      k       Entropy         Average k 
  =========   ========   ========   ====================
        1/1    1.07145    5.64881
        2/1    1.06882    7.02126
        3/1    1.06415    7.80456
        4/1    1.05055    8.29263
        5/1    1.03853    8.61027
        .      .          .
        .      .          .
        .      .          .
     1491/1    0.99057    9.36947    0.99062 +/- 0.00003
     1492/1    0.99066    9.36859    0.99062 +/- 0.00003
     1493/1    0.99060    9.36932    0.99062 +/- 0.00003
     1494/1    0.98948    9.36886    0.99062 +/- 0.00003
     1495/1    0.98981    9.36924    0.99062 +/- 0.00003
     1496/1    0.99006    9.37022    0.99062 +/- 0.00003
     1497/1    0.99002    9.37007    0.99062 +/- 0.00003
     1498/1    0.98936    9.36919    0.99062 +/- 0.00003
     1499/1    0.99085    9.36910    0.99062 +/- 0.00003
     1500/1    0.99054    9.36652    0.99062 +/- 0.00003
```
```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   5.68442e+06 +/- 1292.97
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   5.68911e+06 +/- 988.894
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   5.69151e+06 +/- 1287.65
```

**Comment by smharper** [comment] 2019-03-29 16:20
@D-Benjamin, I looked more closely at this issue today and tried to make sense of the numbers you're sharing from the tallies.out.  If I understand correctly, the cell volumes are 333496, 333491, and 333496 cm^3.  That means the power densities from your latest results are
```
(5.68442e+06 +/- 1292.97) / 333496 = 17.045 +/- 0.004
(5.68911e+06 +/- 988.894) / 333491 = 17.059 +/- 0.003
(5.69151e+06 +/- 1287.65) / 333496 = 17.066 +/- 0.004
```
Those power densities are all really close together, on the order of a few standard deviations.  Bearing in mind that those uncertanties are only one standard dev and that they are underestimates (they don't correct for autocorrelation), I wouldn't say those cells have statistically significantly different power levels.  So it looks to me like tallies are giving the expected answer.

**Comment by D-Benjamin** [comment] 2019-03-30 03:40
Hi @paulromano @smharper , I may find the reason. This time, I changed all the boundary types from "reflective" to "vacuum" and I can get nearly perfect result. The result shows below. I think there are two possible reasons.

1. 

I guess there is a bug exist in "reflective" boundary type, which makes the tally twice or even more near the boundary. Well, it's just my guess. I don't have enough knowledge of the theory of the Monte Carlo method, so I can not understand the source code of OpenMC. I hope you can check it and verify it's correctness.

2. 

If there isn't a bug of "reflective" boundary type, I guess the reason is that this model is not suitable for completely reflective boundary type. But, I think the possibility of the reason one is bigger.

In order to demonstrate my conjecture, I did an another test. I replaced the "reflective" boundary type by a special structure material which is used for the reflector in the nuclear reactor. Fortunately, I can get the ideal result. I plot it but it has no ways to upload it by github.

Following is the result of changing all the boundary types from "reflective" to "vacuum":
```
 =====================>     TALLY 1: CORE KAPPA0     <======================

 Cell 0
   Total Material
     Kappa-Fission Rate                   4.16123e+06 +/- 8279
 =====================>     TALLY 10: CORE KAPPA3     <=====================

 Cell 3
   Total Material
     Kappa-Fission Rate                   8.07722e+06 +/- 10084.3
 =====================>     TALLY 19: CORE KAPPA6     <=====================

 Cell 6
   Total Material
     Kappa-Fission Rate                   4.1985e+06 +/- 8696.56
```
Power density(W/m3) shows below:
```
51489 37084 13308
99943 71177 25492
51949 36938 13310
```

**Comment by smharper** [comment] 2019-03-31 11:10
@D-Benjamin, reflective BCs take 100% of the neutrons that touch that surface and send them back into the geometry.  It's used when you want to take advantage of symmetry in your model.  For example, if your reactor core is symmetric about x=0, then you can model just the parts that are located at x>0 and use a reflective BC at x=0.

So in your original model, it's effectively like OpenMC was modeling a reactor of infinite height---neutrons never leak out of the system vertically.  Therefore, the power density should be the same at all z values.  Of course, this 100% reflection isn't a good way to simulate reflector materials in real reactors.  Real reflectors absorb some of the neutrons that enter them.

I'm

**Comment by smharper** [comment] 2019-03-31 11:13
This isn't a bug so I'm going to close the issue now.  If you'd like to talk about this further, I would encourage you to make a post on the [users group](https://groups.google.com/forum/#!forum/openmc-users).

**Closed by smharper** 2019-03-31 11:13 UTC
