### ISSUE TITLE
shall we move to a src folder layout for the python package

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#2258] opened 2022-10-07 17:03 UTC
While attempting to make a pip install for openmc I came across this problem where I kept importing the local folder instead of the pip installed package. I am now thinking we should probably move to a src folder layout

```
├─ src
│  └─ openmc
│     ├─ __init__.py
│     └─ ...
├─ tests
│  └─ ...
└─ setup.py
```

There are several reasons this is now the [recommended](https://packaging.python.org/en/latest/tutorials/packaging-projects/) package layout for python which are well described elsewhere [[1]](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure), 

But the main sticking point of the current layout is that python adds the local openmc folder as a package.
We are not testing what we think we are testing and we are not importing what we think we are importing.

when in the root folder running a pip install or even a pip install -e . will install the package to our python path. Then running commands like ```pytest test``` from the same folder or ```python -c "import openmc"``` are all importing the packaging in the local folder. We are not actually testing the installed package as a user would import it.

**Comment by paulromano** [comment] 2022-10-08 11:22
Closing as this is a duplicate of #1226, but yes, we should. I've just been hesitating on this for fear of messing up all the open PRs

**Closed by paulromano** 2022-10-08 11:22 UTC
